version: '3'
services:
    island:
      image: ark-base
      environment:
        SERVER_NAME: "Verdent Island"
        SERVER_PASSWORD: ${ark_server_pass}
        ADMIN_PASSWORD: ${ark_admin_pass}
        CLUSTER_NAME: "Verdent_cluster"
        QUERY_PORT: "27001"
      ports:
        - "7777:7777/udp"
        - "7778:7778/udp"
        - "27001:27001/udp"
      volumes:
        - ArkClusterData:/home/steam/clusterdata
        - ArkIslandServer:/home/steam/saves

    extinction:
      image: ark-base
      environment:
        MAP: "Extinction"
        SERVER_NAME: "Verdent Extinction"
        SERVER_PASSWORD: ${ark_server_pass}
        ADMIN_PASSWORD: ${ark_admin_pass}
        PORT: "7780"
        QUERY_PORT: "27002"
        RCON_PORT: "32332"
        CLUSTER_NAME: "Verdent_cluster"
      ports:
        - "7780:7780/udp"
        - "7781:7781/udp"
        - "27002:27002/udp"
      volumes:
        - ArkClusterData:/home/steam/clusterdata
        - ArkExtinctionServer:/home/steam/saves

volumes:
    ArkClusterData:
    ArkIslandServer:
    ArkExtinctionServer:
